### ISSUE TITLE
Are you going to make a browserhax version for 11.15

### ISSUE THREAD

**Issue by jdev082** [zoogie/web#7]
I didn't know where to ask, but I found here.
I unknowingly applied 11.15 to my 3DS, then I found browserhax AFTERWARDS. So, if you can please make a version for 11.15. So I can be on my way making my 3DS not as obsolete as it is right now.

**Comment by jdev082** [comment]
its a New Nintendo 3DS XL

**Comment by zoogie** [comment]
You don't have to wait for browserhax to return:
https://3ds.hacks.guide
There are other free methods that work on latest firm at that link.

I don't know if I'll even be bringing browserhax back. I'm evaluating multiple options.
